NGSimulator {
    seed = 42
    outputDirectory = "outputs"
    NetModel {
        distanceSpreadThreshold = 0.05
        numberOfExperiments = 10
        perturbationCoefficient = 0.3
        dissimulationCoefficient = 0.15
        distanceCoefficient = 0.2
        edgeProbability = 0.001
        statesTotal = 10
        desiredReachabilityCoverage = 1.0
        numberOfWalks = 10
        maxBranchingFactor = 3
        maxDepth = 3
        maxProperties = 5
        propValueRange = 10
        actionType = 5
        actionRange = 3
        connectedness = 2
        maxWalkPathLengthCoeff = 2
        graphWalkTerminationPolicy = ${NGSimulator.Constants.MaxPathLength}
        graphWalkNodeTerminationProbability = 0.001d
        valuableDataProbability = 0.001d
    }
    CostRewards {
        malAppBudget = 100.0
        costOfDetection = 0.2d
        serviceRewardProbability = 0.3
        serviceReward = 10d
        servicePenalty = 3d
        targetAppScore = 5
        targetAppLowPenalty = 1
        targetAppHighPenalty = 2
    }
    Constants {
       MaxPathLength  = "maxpathlength"
       UntilCycle = "untilcycle"
       All = "all"
    }
    Graph {
       directionality = "directed"
       fileName = "example_graph.ngs"
       outputPath = "./converted"
       graphLocation = "../../../"
    }
    OutputGraphRepresentation {
       contentType = "json"
    }
}
